### Login V1 (Admin)

POST localhost:20000/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "application_id": "ai-bot"
}

> {%
    // Save the token to an environment variable
    client.global.set("access_token_admin", response.body.access_token);
%}

### SignUP

POST localhost:20000/api/v1/auth/signup
Content-Type: application/json

{
  "application_id": "ai-bot",
  "username": "user_{{$timestamp}}_{{$randomInt}}",
  "password": "pass"
}

> {%
    // Save the token to an environment variable
    client.global.set("user_id", response.body.id);
    client.global.set("username", response.body.username);
%}

### Login V1
# access_token=$(curl -s --request POST  localhost:20000/api/v1/auth/login -H "Content-Type: application/json" -d '{"username": "user_1","password": "pass","application_id": "ai-bot"}' | jq -r '.access_token'); echo $access_token

POST localhost:20000/api/v1/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "pass",
  "application_id": "ai-bot"
}

> {%
    // Save the token to an environment variable
    client.global.set("access_token", response.body.access_token);
%}

### Request: Get User
# curl localhost:20000/api/v1/user -H "Authorization: Bearer $access_token"
GET localhost:20000/api/v1/user
Authorization: Bearer {{access_token}}
